LIBRARY=libXimd

CSRCS =	FrameMgr.c \
	IMValues.c \
	i18nIMProto.c \
	i18nPtHdr.c \
	i18nX.c \
	IMConn.c \
	i18nAttr.c \
	i18nIc.c \
	IMMethod.c \
	i18nClbk.c \
	i18nMethod.c \
	i18nTr.c \
	i18nUtil.c

INCLUDES += -I.

DEFINES +=
